const lectures = [
  {
    id:'forsokratikerna', no:1, title:'Försokratikerna', subtitle:'Den västerländska filosofins födelse', symbol:'Ω',
    intro:'Från frågan om världens urämne till konflikten mellan förändring och oföränderligt vara. Här börjar kursens stora berättelse.',
    story:['Vad består världen av?','Är verkligheten matematisk?','Kan vi tänka om gudar utan att göra dem mänskliga?','Förändras allt - eller ingenting?','Kan förändring förklaras utan att grunden förändras?','Från naturen till människan och retoriken'],
    clusters:[
      {title:'Miletiska naturfilosofer', question:'Vad är urämnet (fysis) som allt kommer ifrån och består av?', people:[
        {name:'Thales',date:'ca 625-546 f.Kr.',mark:'💧',core:'Urämnet är vatten.',remember:'Det viktiga är inte bara svaret vatten, utan försöket att ge naturen en generell naturlig förklaring.',tags:['fysis','vatten','naturförklaring']},
        {name:'Anaximandros',date:'ca 611-546 f.Kr.',mark:'∞',core:'Urämnet är det oändliga / obestämda.',remember:'Grunden behöver inte själv vara ett vanligt synligt ämne.',tags:['apeiron','obestämt','urämne']},
        {name:'Anaximenes',date:'död ca 528 f.Kr.',mark:'💨',core:'Urämnet är luft.',remember:'Samma grundfråga som hos Thales - ett annat svar.',tags:['luft','fysis']}
      ]},
      {title:'Matematik och religion', question:'Kan verklighetens struktur vara mer abstrakt än materia?', people:[
        {name:'Pythagoras',date:'500-talet f.Kr.',mark:'🎵',core:'Samband mellan tonskalor och matematiska proportioner. Matematisk metafysik: "allt är tal".',remember:'Skilj mellan att världen beskrivs av matematik och den starkare tanken att världen i grunden är matematisk.',tags:['tal','proportion','matematik']},
        {name:'Xenofanes',date:'ca 570-480 f.Kr.',mark:'🐂',core:'Kritiserar antropomorfism: människor föreställer sig gudar utifrån hur människor själva är.',remember:'Om oxar kunde föreställa sig gudar skulle deras gudar likna oxar. Föreläsningen framställer honom som den förste religionsfilosofen.',tags:['antropomorfism','monoteism','religionsfilosofi']}
      ]},
      {title:'Den stora konflikten', question:'Är verkligheten i grunden förändring eller stabilitet?', compare:true, people:[
        {name:'Herakleitos',date:'ca 540-470 f.Kr.',mark:'🔥',core:'Allt är i ständig förändring. Tingen är instabila och övergår i sina motsatser. Logos är den stabila lagen i världsprocessen.',remember:'Tänk process: det stabila är själva förändringsordningen.',tags:['förändring','logos','eld','motsatser']},
        {name:'Parmenides',date:'ca 515-455 f.Kr.',mark:'🪨',core:'Det som är, är. Det som inte är kan inte tänkas. Därför blir verklig förändring problematisk.',remember:'Strikt rationalism: förnuftets argument får slå ut sinnenas vittnesmål.',tags:['vara','ontologi','rationalism','oföränderlighet']}
      ]},
      {title:'Paradoxer och kompromisser', question:'Hur försvarar man Parmenides - och hur försöker andra rädda förändringen?', people:[
        {name:'Zenon',date:'ca 495-445 f.Kr.',mark:'🐢',core:'Försvarar Parmenides med paradoxer om rörelse, bland annat Akilles och sköldpaddan och pilen.',remember:'Metoden: anta motståndarens syn och visa att den leder till absurditet eller paradox.',tags:['paradox','rörelse','Zenon']},
        {name:'Empedokles',date:'400-talet f.Kr.',mark:'🌍',core:'Flera beständiga grundelement kan kombineras på olika sätt.',remember:'Förändringen kan ligga i kombinationerna medan de grundläggande beståndsdelarna förblir desamma.',tags:['element','kombination','förändring']},
        {name:'Anaxagoras',date:'ca 500-428 f.Kr.',mark:'🧩',core:'Grundelementen förändras inte; allt innehåller lite av allt. Nous sätter den ursprungliga rörelsen i gång.',remember:'En modell där en oföränderlig grund kan ge upphov till en föränderliga värld.',tags:['nous','grundelement','rörelse']}
      ]},
      {title:'Atomister och sofister', question:'Hur går vi från naturens minsta delar till människans perspektiv?', people:[
        {name:'Leukippos & Demokritos',date:'400-talet f.Kr.',mark:'⚛',core:'Atomer är odelbara och oföränderliga; de rör sig och kombineras i tomrum.',remember:'Stabilt: atomerna. Förändring: deras rörelser och kombinationer.',tags:['atomer','tomrum','mekanism']},
        {name:'Protagoras & Gorgias',date:'400-talet f.Kr.',mark:'🗣',core:'Sofisterna förknippas med retorik, skepticism/relativism och skillnaden mellan physis och nomos.',remember:'Protagoras: "Människan är alltings mått". Fokus flyttas från kosmos till människan, språket och samhället.',tags:['sofister','retorik','relativism','physis/nomos']}
      ]}
    ],
    quiz:[
      ['Vad är miletarnas gemensamma grundfråga?','Vad urämnet, fysis, är - det som allt kommer ifrån och består av.'],
      ['Vad är den stora skillnaden mellan Herakleitos och Parmenides?','Herakleitos gör förändring grundläggande; Parmenides argumenterar för att verklig förändring är omöjlig.'],
      ['Vad försöker Zenons paradoxer åstadkomma?','De ska försvara Parmenides genom att visa att antagandet om rörelse leder till paradoxer.'],
      ['Vad är atomisternas lösning på förändringsproblemet?','Atomerna själva är oföränderliga, medan deras rörelse och kombinationer förklarar förändringen vi ser.'],
      ['Vad kritiserar Xenofanes?','Antropomorfism - att vi gör gudarna människolika.'],
      ['Vad betyder Pythagoras matematiska metafysik i föreläsningen?','Att universum har underliggande matematiska proportioner, och i en starkare mening kanske är matematiskt i grunden.']
    ]
  },
  {
    id:'sokrates-platon',no:2,title:'Sokrates & Platon',subtitle:'Definitioner, kunskap och idévärld',symbol:'Σ',
    intro:'Sokrates granskar våra övertygelser genom frågor. Platon bygger vidare mot en större teori om kunskap, verklighet och själ.',
    story:['Sokrates metod och apori','Euthyfrons dilemma','Tidiga kontra senare dialoger','Theaitetos: vad är vetande?','Idéläran','Den indelade linjen och grottliknelsen','Själens odödlighet och återerinring'],
    clusters:[
      {title:'Sokrates',question:'Vad händer när vi kräver verkliga definitioner och grunder?',people:[{name:'Sokrates',date:'ca 469-399 f.Kr.',mark:'?',core:'Söker definitioner av centrala begrepp och visar genom kritiska frågor hur svaga grunder våra övertygelser ofta har.',remember:'Tidiga dialoger slutar ofta i apori: man inser att man ännu inte vet.',tags:['definition','apori','kritiska frågor']}]},
      {title:'Euthyfron',question:'Är något gott för att Gud vill det, eller vill Gud det för att det är gott?',people:[{name:'Euthyfrons dilemma',date:'tidig dialog',mark:'⚖',core:'Sokrates skiljer exempel från definition och pressar frågan om fromhetens grund.',remember:'Dilemmat skapar problem för försök att göra moral helt beroende av gudomlig vilja.',tags:['etik','definition','dilemma']}]},
      {title:'Platon och kunskapen',question:'Vad är vetande och vad kan sinnena ge oss?',people:[{name:'Theaitetos',date:'mellandialog',mark:'👁',core:'Förslaget att kunskap är förnimmelse prövas och kritiseras, bland annat via Protagoras och Herakleitos.',remember:'Förnimmelse räcker inte; vi behöver också begrepp som ordnar det sinnliga.',tags:['epistemologi','förnimmelse','Protagoras']},{name:'Idéläran',date:'Platon',mark:'△',core:'Idéerna är tidlösa och begripliga för intellektet; sinnevärlden är en ofullkomlig kopia.',remember:'Skilj idévärld/intellekt från sinnevärld/sinnen.',tags:['former','universalier','idévärld']}]}
    ],
    quiz:[['Vad betyder apori?','Ett tillstånd av förvirring där ingen tillfredsställande definition eller lösning har nåtts.'],['Vad är kärnan i Euthyfrons dilemma?','Om det goda är gott bara för att Gud vill det blir moralen godtycklig; om Gud vill det för att det redan är gott verkar det goda oberoende av Gud.'],['Vad är Platons grundskillnad mellan idévärld och sinnevärld?','Idéerna är tidlösa och förstås med intellektet; sinnevärldens ting är föränderliga och uppfattas med sinnena.']]
  },
  {id:'aristoteles',no:3,title:'Aristoteles',subtitle:'Metod, orsaker och verklighet',symbol:'A',intro:'Aristoteles försöker bevara fenomenen och söka deras första principer med en mer jordnära metod än Platon.',story:['Endoxisk metod','Första principer','Kunskap via varseblivning och abstraktion','De fyra orsakerna','Teleologi','Form och materia','Potentialitet och aktualitet'],clusters:[{title:'Metoden',question:'Hur börjar filosofisk undersökning?',people:[{name:'Endoxisk metod',date:'Aristoteles',mark:'◎',core:'Börja med fenomenen och välgrundade uppfattningar, sök sedan principerna som bäst förklarar dem.',remember:'"Bevara fenomenen": teorin ska så långt möjligt respektera det den ska förklara.',tags:['endoxa','fenomen','principer']}]},{title:'Fyra orsaker',question:'Vad krävs för en fullständig förklaring?',people:[{name:'Materiell',date:'vad av?',mark:'■',core:'Materialet något består av.',remember:'Statyn: brons.',tags:['material']},{name:'Formell',date:'vad är det?',mark:'◇',core:'Formen eller strukturen som gör tinget till vad det är.',remember:'Statyns gestalt.',tags:['form']},{name:'Verkande',date:'vad orsakar?',mark:'→',core:'Källan till förändring eller produktion.',remember:'Skulptören.',tags:['efficient cause']},{name:'Ändamål',date:'varför?',mark:'◎',core:'Syftet, funktionen eller målet.',remember:'Varför statyn görs.',tags:['telos','teleologi']}]},{title:'Potentialitet och aktualitet',question:'Hur kan något förändras utan att bli "ingenting"?',people:[{name:'Potentialitet',date:'dynamis',mark:'○',core:'Vad något kan bli eller göra.',remember:'En kapacitet eller möjlighet i ett ting.',tags:['potentialitet']},{name:'Aktualitet',date:'energeia',mark:'●',core:'När kapaciteten är förverkligad eller i verksamhet.',remember:'Hjälper Aristoteles att analysera förändring.',tags:['aktualitet']}] }],quiz:[['Vilka är de fyra orsakerna?','Materiell, formell, verkande och ändamålsorsak.'],['Vad betyder teleologi hos Aristoteles?','Att naturen förstås i termer av mål, funktioner eller ändamål.'],['Vad är den endoxiska metodens utgångspunkt?','Fenomenen och uppfattningar värda att beakta, som sedan systematiseras mot djupare principer.']]},
  {id:'antikens-etik',no:4,title:'Antikens moralfilosofi',subtitle:'Hur bör vi leva?',symbol:'⚖',intro:'Från Sokrates fråga om livet till Platons själsliga harmoni och Aristoteles eudaimonia och dygder.',story:['Sokrates fråga: hur bör jag leva?','Platon: rättvisa i stat och själ','Den tredelade själen','Aristoteles: det högsta goda','Eudaimonia','Funktionsargumentet','Etiska och intellektuella dygder','Stoiker och epikuréer'],clusters:[{title:'Platon',question:'Vad är rättvisa?',people:[{name:'Rättvisa som harmoni',date:'Staten',mark:'♜',core:'En rättvis stat och en rättvis själ fungerar när deras delar utför sina funktioner på rätt sätt.',remember:'Själen: begär - thumos/kampberedskap - förnuft. Rättvisa är harmoni mellan delarna.',tags:['rättvisa','harmoni','tredelad själ']}]},{title:'Aristoteles',question:'Vad är människans högsta goda?',people:[{name:'Eudaimonia',date:'Nikomachiska etiken',mark:'☀',core:'Lycka/blomstring är att leva och handla väl över ett helt liv.',remember:'Eudaimonia är inte bara en känsla av lycka.',tags:['eudaimonia','blomstring']},{name:'Funktionsargumentet',date:'Bok I',mark:'⚙',core:'Det goda människolivet knyts till människans särskilda funktion: förnuftig aktivitet utförd väl.',remember:'Bra människa = rationell aktivitet i enlighet med dygd.',tags:['funktion','förnuft','dygd']}] }],quiz:[['Vad är eudaimonia?','Ett lyckat eller blomstrande liv, inte bara en serie behagliga känslor.'],['Vad är rättvisa hos Platon på individnivå?','Själslig harmoni där begär, thumos och förnuft fyller sina funktioner i rätt ordning.'],['Vad är kärnan i Aristoteles funktionsargument?','För att veta vad ett gott människoliv är frågar vi efter människans särskilda funktion: rationell aktivitet som utförs väl.']]},
  {id:'descartes',no:5,title:'Descartes',subtitle:'Tvivel, cogito och dualism',symbol:'D',intro:'Descartes vill börja om från grunden och hitta något som inte kan betvivlas.',story:['Skeptisk metod','Sinnena kan bedra','Drömargumentet','Den bedrägliga demonen','Cogito','Jaget som tänkande ting','Vaxargumentet','Själ-kroppsdualism'],clusters:[{title:'Meditationerna',question:'Vad återstår när allt tvivelbart kastas bort?',people:[{name:'Metodiskt tvivel',date:'Första meditationen',mark:'?',core:'Om något går att tvivla på behandlas det tills vidare som falskt.',remember:'Skepticismen används som metod för att hitta visshet - inte som slutmål.',tags:['tvivel','dröm','demon']},{name:'Cogito',date:'Andra meditationen',mark:'I',core:'När jag tänker eller tvivlar måste jag existera som den som tänker.',remember:'Kroppen kan fortfarande betvivlas; det som först säkras är det tänkande jaget.',tags:['cogito','res cogitans']}]},{title:'Intellekt och sinnen',question:'Vad visar vaxklumpen?',people:[{name:'Vaxargumentet',date:'Andra meditationen',mark:'▱',core:'Vaxets sinnliga egenskaper förändras men vi identifierar det ändå som samma vax.',remember:'Descartes använder exemplet för intellektets företräde framför sinnena i förståelsen av ting.',tags:['vax','intellekt','sinnen']}] }],quiz:[['Vad är syftet med Descartes skeptiska metod?','Att hitta en grund som inte kan betvivlas och bygga kunskapen därifrån.'],['Vad visar cogito?','Att jag existerar varje gång jag tänker; själva tänkandet kan inte tvivlas bort medan det pågår.'],['Varför är kroppen inte det första Descartes säkrar?','Kroppen kan fortfarande tänkas vara en illusion; cogito säkrar först det tänkande jaget.']]},
  {id:'spinoza-leibniz',no:6,title:'Spinoza & Leibniz',subtitle:'Rationalismen efter Descartes',symbol:'∞',intro:'Två radikalt olika svar på vad verklighetens grundläggande substanser är.',story:['Spinozas monism','Gud eller naturen','Attribut och modi','Determinism och befrielse','Leibniz monader','Perception och appetition','Tillräckliga grundens princip','Nödvändiga och kontingenta sanningar'],clusters:[{title:'Spinoza',question:'Hur många substanser finns?',people:[{name:'En substans',date:'Etiken',mark:'∞',core:'Det finns bara en nödvändigt existerande substans: Gud eller naturen.',remember:'Tänkande och utsträckning är attribut hos samma substans; vanliga ting är modi.',tags:['monism','substans','attribut','modi']},{name:'Befrielse',date:'Etiken IV-V',mark:'☼',core:'Förnuftig förståelse av nödvändigheten kan minska affekternas makt över oss.',remember:'Spinozas etik kopplar metafysisk förståelse till frigörelse från emotionell träldom.',tags:['affekter','determinism','förnuft']}]},{title:'Leibniz',question:'Hur kan verkligheten bestå av enkla substanser?',people:[{name:'Monader',date:'Monadologin',mark:'•',core:'Monader är enkla, odelbara substanser utan "fönster".',remember:'Varje monad har perceptioner och förändras från en intern princip.',tags:['monad','perception','appetition']}] }],quiz:[['Vad är Spinozas monism?','Att endast en substans finns: Gud eller naturen.'],['Vad är ett modus hos Spinoza?','Ett bestämt sätt den enda substansen uttrycks eller framträder på.'],['Vad menar Leibniz med att monader saknar fönster?','Att inget kan gå in i eller ut ur en monad och påverka den utifrån på vanligt kausalt sätt.']]},
  {id:'locke-berkeley',no:7,title:'Locke & Berkeley',subtitle:'Empirismen del I',symbol:'E',intro:'Kunskapens ursprung flyttas från medfödda idéer till erfarenhet - och Berkeley drar empirismen mot immaterialism.',story:['Tabula rasa','Argument mot medfödda idéer','Sensation och reflection','Enkla och komplexa idéer','Primära och sekundära kvaliteter','Abstraktion','Berkeleys kritik','Esse est percipi'],clusters:[{title:'Locke',question:'Varifrån kommer våra idéer?',people:[{name:'Tabula rasa',date:'Essay',mark:'□',core:'Medvetandet föds utan medfödda idéer; kunskapens material kommer från erfarenhet.',remember:'Två källor: sensation från yttre ting och reflection över det egna medvetandets operationer.',tags:['tabula rasa','sensation','reflection']},{name:'Idéer och kvaliteter',date:'Locke',mark:'◐',core:'Enkla idéer tas emot passivt; komplexa idéer byggs genom att kombinera dem.',remember:'Locke skiljer även mellan primära och sekundära kvaliteter.',tags:['enkla idéer','komplexa idéer','kvaliteter']}]},{title:'Berkeley',question:'Behöver vi anta materiella ting bakom våra idéer?',people:[{name:'Immaterialism',date:'Principles',mark:'👁',core:'Berkeley kritiserar abstrakta idéer och idén om materiell substans.',remember:'Kärnformeln brukar sammanfattas som esse est percipi - att vara är att förnimmas, för sinnliga objekt.',tags:['immaterialism','perception','abstraktion']}] }],quiz:[['Vilka är Lockes två källor till idéer?','Sensation och reflection.'],['Vad betyder tabula rasa?','Att medvetandet inte börjar med medfödda idéer utan får sitt innehåll genom erfarenhet.'],['Vad radikaliserar Berkeley i empirismen?','Han ifrågasätter materiell substans och behandlar sinnliga objekt i termer av idéer/perception.']]},
  {id:'hume',no:8,title:'Hume',subtitle:'Empirismen del II',symbol:'H',intro:'Hume driver det empiristiska programmet längre och granskar idéer, fakta, orsak och människans sätt att dra slutsatser.',story:['Intryck och idéer','Kopieringsprincipen','Relations of ideas','Matters of fact','Orsak och verkan','Induktionsproblemet','Vana och förväntan','Förnuftets gränser'],clusters:[{title:'Perceptionerna',question:'Vad finns i medvetandet?',people:[{name:'Intryck',date:'Hume',mark:'●',core:'Omedelbara och livliga perceptioner: färg, ljud, smak, känslor.',remember:'Intrycken är utgångspunkten.',tags:['impressions','livlighet']},{name:'Idéer',date:'Hume',mark:'○',core:'Svagare kopior av intryck, till exempel minnet eller tanken på en upplevelse.',remember:'Fråga om ett oklart begrepp: vilket intryck kommer idén ifrån?',tags:['ideas','kopieringsprincip']}]},{title:'Fakta och kausalitet',question:'Hur kan vi veta något bortom det vi direkt upplever?',people:[{name:'Relations of ideas',date:'Hume',mark:'=',core:'Sanningar vars negation innebär motsägelse, exempelvis matematiska relationer.',remember:'Nödvändighet genom idéernas relation.',tags:['logik','matematik']},{name:'Matters of fact',date:'Hume',mark:'→',core:'Faktasatser kan negeras utan motsägelse. Våra slutsatser mellan fakta använder kausalitet.',remember:'Kausalitet är inte logisk nödvändighet; erfarenhet och vana spelar central roll.',tags:['fakta','kausalitet','induktion']}] }],quiz:[['Vad är skillnaden mellan intryck och idéer?','Intryck är mer omedelbara och livliga; idéer är svagare kopior eller representationer.'],['Vad är en relation of ideas?','En sanning vars negation innebär logisk motsägelse, som i matematik eller logik.'],['Varför blir kausalitet ett problem för Hume?','För att orsaksrelationen inte kan härledas som en logisk nödvändighet; våra förväntningar går utöver det direkt givna.']]},
  {id:'kant-teoretisk',no:9,title:'Kant: teoretisk filosofi',subtitle:'Den kopernikanska revolutionen',symbol:'K',intro:'Kant försöker förena empirismens erfarenhetskrav med rationalismens a priori-strukturer.',story:['Kopernikansk revolution','Transcendental idealism','Sinnlighet och förstånd','Rum och tid','Kategorier','A priori / a posteriori','Analytiskt / syntetiskt','Syntetiskt a priori','Fenomen och noumen'],clusters:[{title:'Kunskapens två källor',question:'Vad måste samverka för att erfarenhet ska vara möjlig?',people:[{name:'Sinnlighet',date:'Kant',mark:'👁',core:'Passivt mottagande av åskådningar. Rum och tid är åskådningsformer.',remember:'Här ges materialet till erfarenheten.',tags:['åskådning','rum','tid']},{name:'Förstånd',date:'Kant',mark:'⌘',core:'Aktiv tankeförmåga som använder begrepp och kategorier för att ordna åskådningar.',remember:'Begrepp utan åskådningar och åskådningar utan begrepp räcker inte ensamma.',tags:['begrepp','kategorier','syntes']}]},{title:'Två distinktioner',question:'Hur klassificerar Kant kunskap och omdömen?',people:[{name:'A priori / a posteriori',date:'kunskapsteoretisk',mark:'↕',core:'A priori berättigas oberoende av erfarenhet; a posteriori genom erfarenhet.',remember:'Nödvändighet och strikt allmängiltighet signalerar a priori.',tags:['a priori','a posteriori']},{name:'Analytisk / syntetisk',date:'begreppslig',mark:'＋',core:'Analytiskt: predikatet ligger redan i subjektbegreppet. Syntetiskt: predikatet tillför nytt innehåll.',remember:'Kants nyckelfråga blir hur syntetisk kunskap a priori är möjlig.',tags:['analytisk','syntetisk']}] }],quiz:[['Vilka är Kants två kunskapskällor?','Sinnlighet och förstånd.'],['Vad är skillnaden mellan a priori och a posteriori?','A priori berättigas oberoende av erfarenhet; a posteriori genom erfarenhet.'],['Varför är syntetiska a priori-omdömen viktiga för Kant?','De skulle både tillföra nytt innehåll och vara nödvändiga/oberoende av erfarenheten, vilket är centralt för matematik och transcendental filosofi.']]},
  {id:'kant-moral',no:10,title:'Kants moralfilosofi',subtitle:'Plikt, autonomi och kategoriskt imperativ',symbol:'!',intro:'Moralens grund ska inte ligga i känsla eller konsekvenser utan i förnuftets allmängiltiga lagstiftning.',story:['God vilja','Plikt','Pliktenlig / av plikt','Maxim','Hypotetiska imperativ','Kategoriska imperativet','Universaliseringsformeln','Människan som ändamål','Autonomi'],clusters:[{title:'Moralens grund',question:'Vad är gott utan inskränkning?',people:[{name:'God vilja',date:'Grundläggning',mark:'◆',core:'Den goda viljan är god genom själva viljandet, inte genom vad den råkar lyckas åstadkomma.',remember:'Konsekvenser utanför vår kontroll avgör inte viljans moraliska värde.',tags:['god vilja','avsikt']},{name:'Plikt',date:'Kant',mark:'!',core:'När god vilja möter våra böjelser framträder moralen som plikt eller förpliktelse.',remember:'Handla inte bara pliktenligt - moralisk halt kräver handling av plikt.',tags:['plikt','böjelser']}]},{title:'Kategoriska imperativet',question:'Vilken maxim får jag göra till min?',people:[{name:'Universaliseringsformeln',date:'Kant',mark:'∀',core:'Handla endast efter den maxim som du samtidigt kan vilja ska bli allmän lag.',remember:'Testa principen för din handling, inte bara den enskilda konsekvensen.',tags:['maxim','allmän lag']},{name:'Ändamålsformeln',date:'Kant',mark:'♙',core:'Behandla mänskligheten alltid samtidigt som ett ändamål och aldrig enbart som medel.',remember:'Personer har en särskild värdighet eftersom rationell natur är ändamål i sig.',tags:['person','värdighet','ändamål']}] }],quiz:[['Vad är gott utan inskränkning enligt Kant?','En god vilja.'],['Vad är skillnaden mellan att handla pliktenligt och av plikt?','Pliktenligt betyder att handlingen stämmer med plikten; av plikt betyder att plikten själv är motivet.'],['Vad testar universaliseringsformeln?','Om min maxim kan tänkas och viljas som allmän lag för alla rationella varelser.']]},
  {id:'utilitarism-nietzsche',no:11,title:'Bentham, Mill & Nietzsche',subtitle:'Utilitarismen och en motståndare',symbol:'U',intro:'Bentham och Mill gör konsekvenser och lycka centrala. Nietzsche angriper själva sättet att värdera liv genom njutning och lidande.',story:['Hedonism och eudaimonia','Konsekventialism','Benthams nyttoprincip','Lustkalkyl','Universalism','Mills försvar','Högre och lägre njutningar','Nietzsches kritik av hedonism och utilitarism'],clusters:[{title:'Klassisk utilitarism',question:'Vad gör en handling moraliskt riktig?',people:[{name:'Jeremy Bentham',date:'1748-1832',mark:'Σ',core:'Den rätta handlingen maximerar den totala mängden lust/lycka för alla berörda.',remember:'Konsekvenserna är moraliskt avgörande. Fördelningen är sekundär jämfört med totalsumman.',tags:['nyttoprincip','hedonism','konsekventialism']},{name:'John Stuart Mill',date:'1806-1873',mark:'↑',core:'Försvarar utilitarismen men skiljer kvalitativt mellan högre och lägre njutningar.',remember:'Mill accepterar inte att alla njutningar bara skiljer sig i kvantitet.',tags:['utilitarism','högre njutningar','kvalitet']}]},{title:'Motståndaren',question:'Är minimerat lidande verkligen det högsta målet?',people:[{name:'Friedrich Nietzsche',date:'1844-1900',mark:'⚡',core:'Kritiserar filosofier som mäter värde genom lust och lidande och betonar att lidande kan vara en del av mänsklig styrka och skapande.',remember:'Han angriper själva värdemåttet, inte bara en detalj i kalkylen.',tags:['kritik','lidande','värdeskapande']}] }],quiz:[['Vad är nyttoprincipen hos Bentham?','Att välja det alternativ som maximerar den totala mängden lycka/lust för alla berörda.'],['Hur skiljer sig Mill från Bentham om njutning?','Mill menar att njutningar kan skilja sig i kvalitet, inte bara intensitet och varaktighet.'],['Vad riktar Nietzsche kritik mot?','Mot sättet att göra lust, lidande och välbefinnande till det centrala måttet på livets värde.']]},
  {id:'wollstonecraft',no:12,title:'Wollstonecraft',subtitle:'Upplysning och feministisk filosofihistoria',symbol:'W',intro:'Wollstonecraft kopplar förnuft, utbildning och jämlikhet och angriper argument som utestänger kvinnor från utbildning och medborgarskap.',story:['Upplysningens förnuft','Rätt till utbildning','Kritik av Burke och Rousseau','Är kvinnors förnuft annorlunda?','Möjlighet kontra historiskt resultat','Utbildning och samhällsorganisation','Feministisk filosofihistoria och kanon'],clusters:[{title:'Wollstonecrafts argument',question:'Kan man först neka utbildning och sedan använda bristen på prestationer som bevis för bristande förmåga?',people:[{name:'Mary Wollstonecraft',date:'1759-1797',mark:'W',core:'Kvinnors påstådda brist på förnuft kan inte förutsättas. Likvärdig utbildning krävs innan man kan dra slutsatser om kapacitet.',remember:'Historisk frånvaro av kvinnliga bidrag visar inte brist på förmåga om kvinnor samtidigt har nekats möjligheten att utbilda sig och bidra.',tags:['utbildning','förnuft','jämlikhet','upplysning']}]},{title:'Filosofihistoriens kanon',question:'Vilka röster räknas som filosofins historia?',people:[{name:'Feministisk filosofihistoria',date:'metafråga',mark:'📚',core:'Föreläsningen använder Wollstonecraft för att diskutera hur filosofihistorien har skrivits och vilka som räknats in eller ut.',remember:'Fråga inte bara vad en filosof sa - fråga också varför vissa filosofer blev kanoniska och andra osynliga.',tags:['kanon','historieskrivning','feminism']}] }],quiz:[['Vad är kärnan i Wollstonecrafts utbildningsargument?','Man kan inte anta att kvinnor har mindre förnuft när de inte fått likvärdiga möjligheter att utbilda och utveckla det.'],['Varför räcker inte historiskt få kvinnliga bidrag som bevis för mindre kapacitet?','För att historiska möjligheter och utbildningsvillkor varit ojämlika.'],['Vilken större fråga öppnar feministisk filosofihistoria?','Hur kanon har skapats och vilka tänkare som inkluderats eller exkluderats från berättelsen om filosofins historia.']]}
];

const state={current:null,query:''};
const page=document.getElementById('page');
const nav=document.getElementById('lectureNav');
const sidebar=document.getElementById('sidebar');
const progressKey='filosofi-a-study-progress-v1';
let progress=JSON.parse(localStorage.getItem(progressKey)||'{}');

function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function saveProgress(){localStorage.setItem(progressKey,JSON.stringify(progress));renderNav();updateProgress();}
function updateProgress(){const n=lectures.filter(l=>progress[l.id]).length;document.getElementById('progressLabel').textContent=`${n}/12`;document.getElementById('progressBar').style.width=`${n/12*100}%`;}
function lectureSearchText(l){return [l.title,l.subtitle,l.intro,...l.story,...l.clusters.flatMap(c=>[c.title,c.question,...c.people.flatMap(p=>[p.name,p.core,p.remember,...p.tags])])].join(' ').toLowerCase();}
function renderNav(){
  const q=state.query.trim().toLowerCase();
  nav.innerHTML=lectures.filter(l=>!q||lectureSearchText(l).includes(q)).map(l=>`<button class="nav-item ${state.current===l.id?'active':''} ${progress[l.id]?'done':''}" data-route="${l.id}" type="button"><span class="nav-no">${String(l.no).padStart(2,'0')}</span><span class="nav-title"><strong>${esc(l.title)}</strong><small>${esc(l.subtitle)}</small></span><span class="done-dot" aria-label="${progress[l.id]?'Klar':'Inte markerad som klar'}"></span></button>`).join('');
  nav.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.route)));
}
function go(id){location.hash=id;sidebar.classList.remove('open');}
function personCard(p){return `<article class="person-card"><div class="person-top"><div class="portrait">${esc(p.mark)}</div><div><h4>${esc(p.name)}</h4><div class="date">${esc(p.date)}</div></div></div><div class="core">${esc(p.core)}</div><div class="remember"><strong>Det här ska sitta:</strong> ${esc(p.remember)}</div><div class="tags">${p.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></article>`;}
function renderLecture(l){
  state.current=l.id;document.title=`${l.title} – Filosofi A`;document.getElementById('breadcrumb').textContent=`Filosofins historia · Föreläsning ${l.no}`;renderNav();
  const story=l.story.map((s,i)=>`<article class="story-step"><span class="step-no">STEG ${i+1}</span><strong>${esc(s)}</strong><p>${i===0?'Börja med frågan. Lägg detaljerna ovanpå efteråt.':'Se hur detta följer på föregående problem.'}</p></article>`).join('');
  const clusters=l.clusters.map((c,ci)=>{
    if(c.compare&&c.people.length===2){return `<section class="section"><div class="section-title"><div><h2>${esc(c.title)}</h2><p>${esc(c.question)}</p></div></div><div class="compare"><div class="compare-side hot"><h3>${esc(c.people[0].name)}</h3><p>${esc(c.people[0].core)}</p><div class="tags">${c.people[0].tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div><div class="versus">VS</div><div class="compare-side cool"><h3>${esc(c.people[1].name)}</h3><p>${esc(c.people[1].core)}</p><div class="tags">${c.people[1].tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div></div><div class="cluster"><div class="cluster-body">${c.people.map(personCard).join('')}</div></div></section>`}
    return `<section class="cluster"><div class="cluster-head"><div><h3>${esc(c.title)}</h3><p>${esc(c.question)}</p></div><button class="cluster-toggle" type="button" data-cluster="${ci}">Dölj</button></div><div class="cluster-body" data-cluster-body="${ci}">${c.people.map(personCard).join('')}</div></section>`;
  }).join('');
  const flashes=l.quiz.slice(0,4).map((q,i)=>`<button class="flashcard" type="button"><span class="eyebrow">Fråga ${i+1}</span><div class="prompt"><strong>${esc(q[0])}</strong></div><div class="answer">${esc(q[1])}</div></button>`).join('');
  page.innerHTML=`
    <section class="hero"><div class="hero-grid"><div><span class="eyebrow">Föreläsning ${l.no} · PDF → studieatlas</span><h1>${esc(l.title)}</h1><p>${esc(l.intro)}</p><div class="hero-actions"><button class="primary-btn" id="startQuiz" type="button">🎯 Testa mig på denna</button><button class="secondary-btn" id="markDone" type="button">${progress[l.id]?'✓ Markerad som klar':'Markera som klar'}</button></div></div><div class="hero-visual" aria-hidden="true"><div class="symbol">${esc(l.symbol)}</div></div></div></section>
    <section class="section"><div class="section-title"><div><h2>Berättelsen först</h2><p>Detta är din mentala ryggrad. Memorera ordningen före detaljerna.</p></div></div><div class="story-strip">${story}</div></section>
    <section class="section"><div class="question-box"><h3>Så ska du läsa den här föreläsningen</h3><p>1) Lär dig problemet. 2) Koppla rätt filosof till rätt svar. 3) Förstå argumentet. 4) Memorera bara nyckelbegreppen. Klicka på korten och testa aktiv återkallning i stället för att läsa PDF-sidorna passivt.</p></div></section>
    <section class="section"><div class="section-title"><div><h2>Filosofer och idéer</h2><p>Klickbara grupper från föreläsningens innehåll.</p></div></div>${clusters}</section>
    <section class="section"><div class="section-title"><div><h2>Kan du återkalla det?</h2><p>Klicka på ett kort för att avslöja svaret.</p></div></div><div class="flash-grid">${flashes}</div></section>
    <section class="section"><div class="mark-row"><p><strong>Färdig med föreläsningen?</strong><br><span style="color:var(--muted);font-size:13px">Markeringen sparas bara i din webbläsare.</span></p><button class="primary-btn" id="markDoneBottom" type="button">${progress[l.id]?'✓ Klar':'Markera som klar'}</button></div></section>`;
  page.querySelectorAll('.cluster-toggle').forEach(btn=>btn.addEventListener('click',()=>{const body=page.querySelector(`[data-cluster-body="${btn.dataset.cluster}"]`);body.classList.toggle('hidden');btn.textContent=body.classList.contains('hidden')?'Visa':'Dölj';}));
  page.querySelectorAll('.flashcard').forEach(card=>card.addEventListener('click',()=>card.classList.toggle('revealed')));
  const toggleDone=()=>{progress[l.id]=!progress[l.id];saveProgress();renderLecture(l);};
  document.getElementById('markDone').addEventListener('click',toggleDone);document.getElementById('markDoneBottom').addEventListener('click',toggleDone);document.getElementById('startQuiz').addEventListener('click',()=>openQuiz(l));
}
function renderHome(){state.current='home';document.title='Filosofi A – Studieatlas';document.getElementById('breadcrumb').textContent='Filosofins historia';renderNav();page.innerHTML=`<section class="hero"><div class="hero-grid"><div><span class="eyebrow">Umeå universitet · Filosofi A</span><h1>Filosofins historia som en karta, inte en hög PDF:er.</h1><p>Välj en föreläsning. Varje sida reducerar PDF:n till en berättelse, filosofer, kärnargument, minneskrokar och självtest. Målet är att du ska kunna navigera idéhistorien från huvudet.</p><div class="hero-actions"><button class="primary-btn" id="continueBtn" type="button">Börja med Försokratikerna</button></div></div><div class="hero-visual"><div class="symbol">Φ</div></div></div></section><section class="section"><div class="section-title"><div><h2>12 föreläsningar</h2><p>Klicka dig igenom kursens idéhistoriska ryggrad.</p></div></div><div class="lecture-grid">${lectures.map(l=>`<article class="lecture-card"><span class="num">${String(l.no).padStart(2,'0')}</span><h3>${esc(l.title)}</h3><p>${esc(l.subtitle)}</p><div class="tags">${l.story.slice(0,3).map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</div><button class="secondary-btn" data-open="${l.id}" type="button">Öppna →</button></article>`).join('')}</div></section>`;document.getElementById('continueBtn').addEventListener('click',()=>go('forsokratikerna'));page.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.open)));}
function openQuiz(l){const dialog=document.getElementById('quizDialog');let idx=0;const body=document.getElementById('quizBody');document.getElementById('quizTitle').textContent=l.title;function draw(){const q=l.quiz[idx];body.innerHTML=`<div class="quiz-card"><div class="quiz-q">${esc(q[0])}</div><div class="quiz-answer" id="quizAnswer">${esc(q[1])}</div><div class="quiz-actions"><button class="primary-btn" id="revealQuiz" type="button">Visa svar</button><button class="secondary-btn" id="nextQuiz" type="button">Nästa fråga</button></div><div class="date" style="margin-top:14px">${idx+1} / ${l.quiz.length}</div></div>`;body.querySelector('#revealQuiz').addEventListener('click',()=>body.querySelector('#quizAnswer').classList.add('show'));body.querySelector('#nextQuiz').addEventListener('click',()=>{idx=(idx+1)%l.quiz.length;draw();});}draw();dialog.showModal();}
function route(){const id=location.hash.replace('#','');if(!id){renderHome();return;}const l=lectures.find(x=>x.id===id);l?renderLecture(l):renderHome();}

document.getElementById('searchInput').addEventListener('input',e=>{state.query=e.target.value;renderNav();});
document.getElementById('menuButton').addEventListener('click',()=>sidebar.classList.toggle('open'));
document.getElementById('studyModeBtn').addEventListener('click',()=>{const l=lectures.find(x=>x.id===state.current)||lectures[0];openQuiz(l);});
document.getElementById('closeQuiz').addEventListener('click',()=>document.getElementById('quizDialog').close());
document.getElementById('resetProgress').addEventListener('click',()=>{if(confirm('Nollställa alla klarmarkeringar?')){progress={};saveProgress();route();}});
window.addEventListener('hashchange',route);renderNav();updateProgress();route();
