const modules=[
{id:'start',title:'Tes, argument & struktur',sub:'Björnsson s. 11–20',status:'current'},
{id:'procontra',title:'Pro & contra',sub:'Sortera stöd och invändningar',status:'ready'},
{id:'under',title:'Underargument',sub:'P → C → T',status:'ready'},
{id:'hold',title:'Hållbarhet',sub:'Kommer i nästa läsblock',status:'future'},
{id:'relevans',title:'Relevans',sub:'Kommer i nästa läsblock',status:'future'},
{id:'bevis',title:'Beviskraft',sub:'Byggs efter hållbarhet + relevans',status:'future'},
{id:'fallasier',title:'Argumentationsfel',sub:'Senare i kursen',status:'future'},
{id:'retorik',title:'Retorik',sub:'Senare i kursen',status:'future'},
{id:'definitioner',title:'Definitioner',sub:'Senare i kursen',status:'future'},
{id:'logik',title:'Grundläggande logik',sub:'Senare i kursen',status:'future'}
];
const state={scores:JSON.parse(localStorage.getItem('ktScores')||'{}'),module:'start'};
const nav=document.getElementById('moduleNav'),view=document.getElementById('view'),crumb=document.getElementById('crumb');
function save(){localStorage.setItem('ktScores',JSON.stringify(state.scores));updateProgress()}
function updateProgress(){const done=Object.values(state.scores).filter(v=>v===true).length;const pct=Math.round(done/3*100);document.getElementById('progressText').textContent=Math.min(pct,100)+'%';document.getElementById('progressBar').style.width=Math.min(pct,100)+'%'}
function renderNav(){nav.innerHTML=modules.map(m=>`<button class="mod-btn ${m.id===state.module?'active':''}" data-id="${m.id}" type="button">${m.status==='future'?'<span class="lock">○</span>':''}${m.title}<small>${m.sub}</small></button>`).join('');nav.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{state.module=b.dataset.id;renderNav();render()}))}
const roles=['Tes','Premiss','Slutsats'];
function roleExercise(){return `<div class="exercise" data-ex="roles"><div class="exercise-head"><div><h3>Övning 1 · Hitta rollerna</h3><p class="section-lead">Markera varje mening. Samma påstående kan vara en slutsats i ett delargument och sedan användas som skäl i ett större argument.</p></div><span class="score">3 meningar</span></div><div class="sentence-list">
${sentence('r1','Universitetet borde spela in alla föreläsningar.','Tes')}
${sentence('r2','Många studenter arbetar vid sidan av studierna.','Premiss')}
${sentence('r3','Därför kan de inte alltid delta live.','Slutsats')}
</div><div class="actions"><button class="primary check-roles" type="button">Kontrollera</button><button class="secondary reset-roles" type="button">Försök igen</button></div><div class="feedback role-feedback"></div></div>`}
function sentence(id,text,correct){return `<div class="sentence" data-id="${id}" data-correct="${correct}"><span>${text}</span><div class="role-buttons">${roles.map(r=>`<button type="button" data-role="${r}">${r}</button>`).join('')}</div></div>`}
function chainExercise(){return `<div class="exercise" data-ex="chain"><div class="exercise-head"><div><h3>Övning 2 · Se hierarkin</h3><p class="section-lead">Vilken struktur beskriver argumentet bäst?</p></div><span class="score">1 val</span></div><div class="flow"><span class="node">P1: Studenter arbetar</span><span class="arrow">→</span><span class="node">C1: Kan inte alltid delta</span><span class="arrow">→</span><span class="node">T: Föreläsningar bör spelas in</span></div><div class="choices chain-choices"><button class="choice" data-ok="false" type="button">Alla tre är separata argument direkt för tesen.</button><button class="choice" data-ok="true" type="button">P1 stöder C1, och C1 stöder sedan tesen.</button><button class="choice" data-ok="false" type="button">Tesen stöder C1, som stöder P1.</button></div><div class="feedback chain-feedback"></div></div>`}
function quizBlock(){const qs=[
['Vilket är bäst beskrivet som en tes?',['Ett centralt påstående som argumentationen försöker försvara eller angripa.','Vilken mening som helst i texten.','All bakgrundsinformation.'],0],
['Vad är ett argument i den här kursens mening?',['Ett gräl mellan två personer.','Ett skäl som talar för eller emot ett påstående.','En lång text.'],1],
['Kan ett påstående både vara slutsats och senare fungera som premiss?',['Ja.','Nej, aldrig.'],0],
['Vad gör du först i en beskrivande argumentationsanalys?',['Bestämmer om du håller med.','Identifierar tes och hur argumenten är strukturerade.','Söker efter retoriska knep.'],1]
];return `<div class="exercise"><div class="exercise-head"><div><h3>Snabbtest · Sitter grunden?</h3><p class="section-lead">Fyra frågor. Målet är att kunna strukturen utan att gissa.</p></div></div>${qs.map((q,i)=>`<div class="quiz-q" data-answer="${q[2]}"><strong>${i+1}. ${q[0]}</strong><div class="choices">${q[1].map((x,j)=>`<button type="button" class="choice" data-i="${j}">${x}</button>`).join('')}</div></div>`).join('')}<div class="done-banner hidden" id="quizDone"></div></div>`}
function startPage(){return `<div class="hero"><div class="hero-card"><span class="eyebrow">Modul 1 · Grunden</span><h1>Se argumentets struktur</h1><p>Du ska inte bara läsa en text. Du ska kunna plocka ut <strong>vad som hävdas</strong>, <strong>vilka skäl som ges</strong> och <strong>vad som stöder vad</strong>.</p></div><div class="reading"><small>Läsning du gjort</small><strong>Björnsson s. 11–20</strong><span>Fokus: påståenden, tes, argument och struktur. Vi tränar färdigheten här i stället för att memorera texten.</span></div></div>
<div class="section"><h2>Tre saker ska sitta</h2><div class="concept-grid"><div class="card"><div class="symbol">🎯</div><h3>Tes</h3><p>Det centrala påståendet som argumentationen försöker få oss att acceptera eller förkasta.</p><div class="mini">Fråga: Vad vill texten övertyga mig om?</div></div><div class="card"><div class="symbol">🧱</div><h3>Premiss / skäl</h3><p>Ett påstående som används för att ge stöd åt en slutsats eller tes.</p><div class="mini">Fråga: Varför ska jag tro detta?</div></div><div class="card"><div class="symbol">↳</div><h3>Slutsats</h3><p>Det påstående som följer som ett resultat av ett eller flera skäl. Det kan sedan bli ett skäl i nästa led.</p><div class="mini">Fråga: Vad försöker skälen etablera?</div></div></div></div>
<div class="section"><h2>Den viktiga insikten</h2><div class="callout"><strong>Argument är hierarkiska.</strong> Ett påstående behöver inte bara vara “argument nummer två”. Det kan vara slutsatsen av ett mindre argument och samtidigt fungera som stöd för huvudtesen.</div></div>
<div class="section"><h2>Träna</h2>${roleExercise()}${chainExercise()}${quizBlock()}</div>
<div class="section"><h2>Kursens verktygslåda</h2><p class="section-lead">Det här är riktningen framåt. Vi fyller på varje modul när du läser motsvarande avsnitt.</p>${roadmap()}</div>`}
function roadmap(){return `<div class="roadmap">${modules.map((m,i)=>`<div class="road-item ${m.status==='current'?'current':m.status==='future'?'future':''}"><strong>${i+1}. ${m.title}</strong><span>${m.sub}</span></div>`).join('')}</div>`}
function proContra(){return `<div class="hero-card"><span class="eyebrow">Modul 2</span><h1>Pro- och contraargument</h1><p>När du hittat tesen behöver du se <strong>riktningen</strong>: talar ett påstående för tesen eller emot den?</p></div><div class="section"><h2>Sortera argument</h2><div class="exercise"><h3>Tes: “Universitetet bör spela in alla föreläsningar.”</h3><div class="sentence-list" id="sortList">${sortSentence('Det hjälper studenter att repetera svåra moment.','pro')}${sortSentence('Det kan minska studenternas incitament att delta live.','contra')}${sortSentence('Studenter med arbete kan få bättre tillgång till undervisningen.','pro')}</div><div class="feedback sort-feedback"></div></div></div>`}
function sortSentence(text,correct){return `<div class="sentence" data-correct="${correct}"><span>${text}</span><div class="role-buttons"><button type="button" data-sort="pro">Pro</button><button type="button" data-sort="contra">Contra</button></div></div>`}
function underPage(){return `<div class="hero-card"><span class="eyebrow">Modul 3</span><h1>Underargument</h1><p>Här lär du dig det du redan upptäckte: <strong>P1 → C1 → T</strong>. Ett argument kan stödjas av ett annat argument.</p></div><div class="section"><h2>Se kedjan</h2><div class="flow"><span class="node">P1</span><span class="arrow">→</span><span class="node">C1 / P2</span><span class="arrow">→</span><span class="node">T</span></div><div class="callout" style="margin-top:12px"><strong>C1 har två roller:</strong> den är slutsats i det första ledet, men fungerar som premiss/skäl när argumentationen går vidare mot tesen.</div></div>`}
function futurePage(m){return `<div class="hero-card"><span class="eyebrow">Kommande modul</span><h1>${m.title}</h1><p>${m.sub}. Vi bygger den här delen utifrån kursens exakta läsanvisningar när du kommer dit, så vi inte blandar in andra modeller eller terminologi än den kursen använder.</p></div><div class="section"><div class="callout"><strong>Inte låst för att vara jobbig.</strong> Vi håller verktygen i rätt ordning: först beskriv argumentet, sedan värdera det.</div></div><div class="section"><h2>Översikt</h2>${roadmap()}</div>`}
function render(){const m=modules.find(x=>x.id===state.module);crumb.textContent=m.title;if(m.id==='start')view.innerHTML=startPage();else if(m.id==='procontra')view.innerHTML=proContra();else if(m.id==='under')view.innerHTML=underPage();else view.innerHTML=futurePage(m);bindInteractions()}
function bindInteractions(){
 document.querySelectorAll('[data-ex="roles"] .role-buttons button').forEach(b=>b.addEventListener('click',()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected')}));
 const check=document.querySelector('.check-roles');if(check)check.addEventListener('click',()=>{let good=0;document.querySelectorAll('[data-ex="roles"] .sentence').forEach(s=>{const sel=s.querySelector('button.selected');s.querySelectorAll('button').forEach(x=>x.classList.remove('correct','wrong'));if(sel){if(sel.dataset.role===s.dataset.correct){sel.classList.add('correct');good++}else sel.classList.add('wrong')}});const f=document.querySelector('.role-feedback');f.classList.add('show');f.textContent=good===3?'Rätt. Du skiljer nu mellan tes, premiss och slutsats.':'Du fick '+good+'/3. Titta på vilken mening som är huvudtes och vilken som följer av “därför”.';if(good===3){state.scores.roles=true;save()}});
 const reset=document.querySelector('.reset-roles');if(reset)reset.addEventListener('click',()=>{document.querySelectorAll('[data-ex="roles"] button').forEach(x=>x.classList.remove('selected','correct','wrong'));const f=document.querySelector('.role-feedback');f.classList.remove('show')});
 document.querySelectorAll('.chain-choices .choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.chain-choices .choice').forEach(x=>x.classList.remove('correct','wrong'));const ok=b.dataset.ok==='true';b.classList.add(ok?'correct':'wrong');const f=document.querySelector('.chain-feedback');f.classList.add('show');f.textContent=ok?'Precis: P1 → C1 → T. Det är hierarkin.':'Inte riktigt. “Därför” visar att den andra meningen är en slutsats av den första.';if(ok){state.scores.chain=true;save()}}));
 document.querySelectorAll('.quiz-q .choice').forEach(b=>b.addEventListener('click',()=>{const q=b.closest('.quiz-q'),ans=Number(q.dataset.answer);q.querySelectorAll('.choice').forEach((x,i)=>{x.classList.remove('correct','wrong');if(i===ans)x.classList.add('correct')});if(Number(b.dataset.i)!==ans)b.classList.add('wrong');const all=[...document.querySelectorAll('.quiz-q')];const answered=all.filter(x=>x.querySelector('.choice.correct')).length;if(answered===all.length){document.getElementById('quizDone').classList.remove('hidden');document.getElementById('quizDone').textContent='Bra. Du har gått igenom hela snabbtestet.';state.scores.quiz=true;save()}}));
 document.querySelectorAll('#sortList .role-buttons button').forEach(b=>b.addEventListener('click',()=>{const s=b.closest('.sentence');s.querySelectorAll('button').forEach(x=>x.classList.remove('correct','wrong'));const ok=b.dataset.sort===s.dataset.correct;b.classList.add(ok?'correct':'wrong');const rows=[...document.querySelectorAll('#sortList .sentence')],done=rows.every(r=>r.querySelector('button.correct'));if(done){const f=document.querySelector('.sort-feedback');f.classList.add('show');f.textContent='Rätt. Du ser nu argumentens riktning: stöd eller invändning.'}}));
}
document.getElementById('resetBtn').addEventListener('click',()=>{if(confirm('Nollställa sparad träning?')){state.scores={};save();render()}});document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('side').classList.toggle('open'));renderNav();render();updateProgress();