name: Security checks
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: 'false'
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: 'false'
          GITLEAKS_ENABLE_SUMMARY: 'true'
      - name: Trivy
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,secret,misconfig
          skip-dirs: .git
          severity: HIGH,CRITICAL
          exit-code: '1'
